name: Build Folder

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      actions: write
    steps:
 
    # You might want to Checkout your repo first, but not mandatory
    - name: Check Out
      uses: actions/checkout@v4

    - name: Build Folder
      run: |
       git clone https://github.com/Aflaungos/m23xq_unica_patches -b main m23xq_unica_patches
       cd $GITHUB_WORKSPACE/m23xq_unica_patches
       zip -r m23xq.zip . -x "overlay*" -x "patches*" -x "config.sh" -x "sff.sh" -x "debloat.sh"

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        name: M23 Hidden Mods
        tag_name: ${{ github.run_id }}
        files: |
          m23xq_unica_patches/m23xq.zip

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 2
        keep_minimum_runs: 1
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

    - name: Delete older releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 1
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
